// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyvNE9jtyZyVZTnyXo-s8YFWrzId7tR0',
    appId: '1:174151480112:web:ff9b1de8c6c124a12e8ef5',
    messagingSenderId: '174151480112',
    projectId: 'signup-1e8a0',
    authDomain: 'signup-1e8a0.firebaseapp.com',
    storageBucket: 'signup-1e8a0.appspot.com',
    measurementId: 'G-VDNDZRW8QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8CNOCNPJQY6fHSPbd_XSd5i8m-BtSPj8',
    appId: '1:174151480112:android:30aab99abf124e3e2e8ef5',
    messagingSenderId: '174151480112',
    projectId: 'signup-1e8a0',
    storageBucket: 'signup-1e8a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7DII0Xb_RLoq2WZZZQ9Vl4XSMc2zbVBc',
    appId: '1:174151480112:ios:924a8eaa5ab8b62e2e8ef5',
    messagingSenderId: '174151480112',
    projectId: 'signup-1e8a0',
    storageBucket: 'signup-1e8a0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7DII0Xb_RLoq2WZZZQ9Vl4XSMc2zbVBc',
    appId: '1:174151480112:ios:924a8eaa5ab8b62e2e8ef5',
    messagingSenderId: '174151480112',
    projectId: 'signup-1e8a0',
    storageBucket: 'signup-1e8a0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHyvNE9jtyZyVZTnyXo-s8YFWrzId7tR0',
    appId: '1:174151480112:web:61d9e3d57bd458132e8ef5',
    messagingSenderId: '174151480112',
    projectId: 'signup-1e8a0',
    authDomain: 'signup-1e8a0.firebaseapp.com',
    storageBucket: 'signup-1e8a0.appspot.com',
    measurementId: 'G-EJ6K1ZFSHH',
  );
}
